- name: setup debian desktop
  hosts: localhost
  become: true
  roles:
    - update
    - network 
    - wm
    - ime
    - firefox
    - zed    
    - config
  vars:
    login_username: "{{ lookup('ansible.builtin.env', 'LOGIN_USERNAME') }}"
    login_home: "/home/{{ lookup('ansible.builtin.env', 'LOGIN_USERNAME') }}"
