- name: setup debian desktop
  hosts: localhost
  become: true
  roles:
    - update
    - network 
    - xfce
    - misc
    - firefox
    - gh
    - zed    
    - user
  vars:
    login_username: "{{ lookup('ansible.builtin.env', 'LOGIN_USERNAME') }}"
    login_home: "/home/{{ lookup('ansible.builtin.env', 'LOGIN_USERNAME') }}"
