- name: install xfce and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - lightdm
    - lightdm-gtk-greeter
    - xfce4
    - xfce4-goodies

- name: configure lightdm
  ansible.builtin.ini_file:
    path: /etc/lightdm/lightdm.conf
    section: "Seat:*"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    mode: "0644"
    create: true
  loop:
    - { option: "greeter-hide-users", value: "false" }
    - { option: "greeter-show-manual-login", value: "false" }
    - { option: "allow-guest", value: "false" }

- name: enable lightdm
  service:
    name: lightdm
    enabled: true

