- name: install xfce and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - lightdm
    - lightdm-gtk-greeter
    - xfce4
    - xfce4-goodies
    - network-manager-applet
    - gnome-keyring
    - libsecret-1-0
    - libpam-gnome-keyring

- name: configure lightdm
  ansible.builtin.ini_file:
    path: /etc/lightdm/lightdm.conf
    section: "Seat:*"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    mode: "0644"
    create: true
  loop:
    - { option: "greeter-hide-users", value: "false" }
    - { option: "greeter-show-manual-login", value: "false" }
    - { option: "allow-guest", value: "false" }

- name: enable lightdm
  service:
    name: lightdm
    enabled: true

- name: create work directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - /tmp/Fluent-gtk-theme
    - /tmp/Fluent-icon-theme

- name: clone gtk theme and icon theme
  ansible.builtin.git:
    repo: "https://github.com/vinceliuice/{{ item }}.git"
    dest: "/tmp/{{ item }}"
  with_items:
    - Fluent-gtk-theme
    - Fluent-icon-theme

- name: run gtk theme install script
  command:
    argv:
      - /tmp/Fluent-gtk-theme/install.sh
      - --tweaks
      - noborder

- name: run icon theme install script
  command:
    argv:
      - /tmp/Fluent-icon-theme/install.sh
  
    
