---
- name: run xdg-user-dirs-update in LANG=C.UTF-8
  become: true
  become_user: "{{ login_username }}"
  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
  command:
    argv:
      - xdg-user-dirs-update
      - --force  

- name: copy .Xresources
  ansible.builtin.template:
    src: "dot.Xresources.j2"
    dest: "{{ login_home }}/.Xresources"
    owner: "{{ login_username }}"
    group: "{{ login_username }}"
    mode: "0644"

- name: create service directory
  ansible.builtin.file:
    path: "{{ login_home }}/opt/user-initial-setup/"
    state: directory
    owner: "{{ login_username }}"
    group: "{{ login_username }}"
    mode: "0755"

- name: copy user-initial-setup files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ login_home }}/opt/user-initial-setup/{{ item }}"
    owner: "{{ login_username }}"
    group: "{{ login_username }}"
    mode: "0644"
  with_items:
    - user-initial-setup.service
    - config.sh
    - service.sh

- name: create user systemd directory
  ansible.builtin.file:
    path: "{{ login_home }}/.config/systemd/user/default.target.wants/"
    state: directory
    owner: "{{ login_username }}"
    group: "{{ login_username }}"
    mode: "0755"

- name: copy service
  ansible.builtin.template:
    src: user-initial-setup.service.j2
    dest: "{{ login_home }}/.config/systemd/user/user-initial-setup.service"
    owner: "{{ login_username }}"
    group: "{{ login_username }}"
    mode: "0644"

- name: enable user service
  file:
    src: "{{ login_home }}/.config/systemd/user/user-initial-setup.service"
    dest: "{{ login_home }}/.config/systemd/user/default.target.wants/user-initial-setup.service"
    state: link
    owner: "{{ login_username }}"
    group: "{{ login_username }}"

- name: create fcitx5 config directory
  ansible.builtin.file:
    path: "{{ login_home }}/.config/fcitx5/conf/"
    state: directory
    owner: "{{ login_username }}"
    group: "{{ login_username }}"
    mode: "0755"

- name: copy config file
  ansible.builtin.template:
    src: "xim.conf.j2"
    dest: "{{ login_home }}/.config/fcitx5/conf/xim.conf"
    owner: "{{ login_username }}"
    group: "{{ login_username }}"
    mode: "0644"

- name: clone .emacs.d
  ansible.builtin.git:
    repo: "https://github.com/wataken44/dot.emacs.d3.git"
    dest: "{{ login_home }}/Documents/dot.emacs.d3/"
  become: true
  become_user: "{{ login_username }}"

- name: create symbolic link
  file:
    src: "{{ login_home }}/Documents/dot.emacs.d3/"
    dest: "{{ login_home }}/.emacs.d"
    state: link
    owner: "{{ login_username }}"
    group: "{{ login_username }}"

- name: clone .zshrc
  ansible.builtin.git:
    repo: "https://github.com/wataken44/dot.zshrc.git"
    dest: "{{ login_home }}/Documents/dot.zshrc/"
  become: true
  become_user: "{{ login_username }}"

- name: create symbolic link
  file:
    src: "{{ login_home }}/Documents/dot.zshrc/.zshrc"
    dest: "{{ login_home }}/.zshrc"
    state: link
    owner: "{{ login_username }}"
    group: "{{ login_username }}"

- name: Change login shell to zsh
  ansible.builtin.user:
    name: "{{ login_username }}"
    shell: /usr/bin/zsh
