# install packages which requires no configuration

- name: install japanese input and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - fcitx5
    - fcitx5-configtool
    - fcitx5-mozc
    - fcitx5-frontend-all
    - fonts-noto-cjk
    - fonts-noto-color-emoji

- name: install emacs and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - emacs
    - emacs-mozc

- name: install zsh
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
