- name: install xfce and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings
    - xfce4
    - xfce4-goodies
    - thunar
    - xfce4-terminal

- name: enable lightdm
  service:
    name: lightdm
    enabled: true
