- name: install NetworkManager
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - network-manager

- name: Configure /etc/network/interfaces for NetworkManager
  ansible.builtin.copy:
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: "0644"
    content: |
      # interfaces are managed by NetworkManager, so loopback only.
      auto lo
      iface lo inet loopback

- name: enable and start NetworkManager
  service:
    name: NetworkManager
    state: restarted
    enabled: true

- name: copy reset script
  ansible.builtin.template:
    src: "reset_network_connection.py"
    dest: "/tmp/"

- name: run script
  command:
    argv:
      - python3
      - /tmp/reset_network_connection.py
  
    
